# Generated by Django 5.2.4 on 2025-09-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeDeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('justification', models.TextField()),
                ('nature_des_prestations', models.CharField(choices=[('chef_de_centre', 'Chef de centre'), ('service_distribution', 'Service distribution'), ('service_moyens_generaux', 'Service moyens généraux'), ('prestataire', 'Prestataire')], max_length=100)),
                ('imputation', models.CharField(max_length=50)),
                ('credit', models.CharField(max_length=50)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_beneficiaire', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gest_demande.fournisseur')),
            ],
        ),
    ]
