# Generated by Django 5.2.4 on 2025-09-21 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_demande', '0002_alter_demandedemateriel_numero_lignedecommande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='lignedecommande',
            name='code_article',
        ),
        migrations.RemoveField(
            model_name='lignedecommande',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='lignedecommande',
            name='prix_unitaire',
        ),
        migrations.AddField(
            model_name='lignedecommande',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gest_demande.article'),
        ),
    ]
