# Generated by Django 5.2.4 on 2025-09-22 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_demande', '0004_beneficiaire_alter_demandedemateriel_beneficiaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandedemateriel',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_beneficiaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Beneficiaire',
        ),
    ]
